# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170613_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Level', verbose_name='level'),
        ),
    ]
