# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
        migrations.AddField(
            model_name='item',
            name='item_categories',
            field=models.ManyToManyField(related_name='items', to='auctions.ItemCategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auctions.Auction', verbose_name='Auction'),
        ),
    ]
