# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20170616_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctioneer',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctioneer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctioneer', to='auctions.Auctioneer', verbose_name='Auctioneer'),
        ),
    ]
