# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20170620_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='auctioneer',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
