# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20170622_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auctioneer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.Auctioneer', verbose_name='Auctioneer'),
        ),
    ]
