# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20170622_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buyers_fees',
            field=models.TextField(blank=True, null=True, verbose_name="Buyer's fees"),
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='auction',
            name='off_site_terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Off Site terms and conditions'),
        ),
        migrations.AddField(
            model_name='auction',
            name='summary',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='auction',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Terms and Conditions'),
        ),
    ]
