# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20170627_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioneer',
            name='motto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
