# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20170702_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioneer',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Activated'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_categories',
            field=models.ManyToManyField(related_name='item_categories_many_to_many', to='auctions.ItemCategory'),
        ),
    ]
