# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_itempicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempicture',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
    ]
