# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20170705_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempicture',
            options={'ordering': ('primary', 'order')},
        ),
        migrations.RemoveField(
            model_name='itempicture',
            name='name',
        ),
    ]
