# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_itempicture_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempicture',
            options={'ordering': ('-primary', 'order')},
        ),
    ]
