# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20170705_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempicture',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_pictures', to='auctions.Item', verbose_name='Item'),
        ),
    ]
