# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20170705_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('lot', 'run', 'name')},
        ),
    ]
