# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0030_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='cancelled_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
