# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20170710_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
