# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_bid_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Name')),
                ('address_line1', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=45, null=True, verbose_name='Address line 2')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state_province', models.CharField(blank=True, choices=[('NY', 'New York'), ('QC', 'Quebec')], max_length=2, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, choices=[('CA', 'Canada'), ('US', 'USA')], max_length=2, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
