# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20170715_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioneer',
            name='address',
        ),
    ]
