# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_remove_auctioneer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctioneerAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.Address')),
                ('auctioneer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctioneer_address', to='auctions.Auctioneer', verbose_name='Address')),
            ],
            bases=('auctions.address',),
        ),
        migrations.CreateModel(
            name='AuctioneerShippingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.Address')),
                ('auctioneer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctioneer_shipping_address', to='auctions.Auctioneer', verbose_name='Address')),
            ],
            bases=('auctions.address',),
        ),
    ]
