# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_auctioneeraddress_auctioneershippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
