# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_address_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctioneeraddress',
            options={'ordering': ('-primary',), 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='auctioneershippingaddress',
            options={'ordering': ('-primary',), 'verbose_name': 'Shipping Address', 'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
