# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_auto_20170722_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='auction_end_date',
            new_name='auction_date_end',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='auction_start_date',
            new_name='auction_date_start',
        ),
    ]
