# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 23:46
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_item_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempicture',
            name='picture2',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos'),
        ),
    ]
