# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 23:51
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_itempicture_picture2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempicture',
            name='picture2',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='item'),
        ),
    ]
